// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SceneSkope.PowerBI.Models
{

    /// <summary>
    /// Defines values for DataType.
    /// </summary>
    public static class DataType
    {
        public const string Int64 = "Int64";
        public const string Double = "Double";
        public const string Boolean = "Boolean";
        public const string Datetime = "Datetime";
        public const string String = "String";
        public const string Decimal = "Decimal";
    }
}
