// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace SceneSkope.PowerBI.Models
{

    /// <summary>
    /// Defines values for DefaultRetentionPolicy.
    /// </summary>
    public static class DefaultRetentionPolicy
    {
        public const string None = "None";
        public const string BasicFIFO = "basicFIFO";
    }
}
